import type { Metadata } from "next";
import { Space_Mono, Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CountdownProvider } from "@/utils/Context/CountdownContext";

const workSans = Work_Sans({
    variable: "--font-work-sans",
    subsets: ["latin"],
});

const spaceMono = Space_Mono({
    variable: "--font-space-mono",
    subsets: ["latin"],
    weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.className} ${spaceMono.variable} antialiased bg-background text-default`}>
        <CountdownProvider>
            <Navbar />
            <main className="overflow-x-hidden">
                {children}
            </main>
            <Footer />
        </CountdownProvider>
      </body>
    </html>
  );
}
